---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  annotations: 
    service.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    app: grafana
    component: core
spec:
#  type: NodePort
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
#    nodePort: 31300
  selector:
    app: grafana
    component: core
