---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
  namespace: my-webpage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
      - name: my-web-app
        image: suleimanjr1/my-personal-webapp:1.1
        ports:
        - name: web
          containerPort: 80
        resources:
          requests:
            memory: 50Mi
            cpu: 50m
          limits:
            memory: 100Mi
            cpu: 100m
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 3
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - general
                
---
apiVersion: v1
kind: Service
metadata:
  name: webpage-private-lb
  namespace: my-webpage
  annotations:
    prometheus.io/scrape: 'true'
    service.kubernetes.io/aws-load-balancer-type: nlb
    service.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  type: LoadBalancer
  selector:
    app: my-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: web
      
      
---
apiVersion: v1
kind: Service
metadata:
  name: webpage-public-lb
  namespace: my-webpage
  annotations:
    prometheus.io/scrape: 'true'
    service.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: my-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: web
      

